name: Create Sample File
 
on:
  workflow_dispatch:
 
jobs:
  create-file:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Create a sample text file
      run: echo "This is a sample text file" > .github/workflows/sample.txt
 
    - name: Commit and push the sample text file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .github/workflows/sample.txt
        git commit -m "Add sample text file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

